/* Triple R Trailers dealer locations.
   To put a dealer on the map, fill in city, state, phone, lat, lng.
   Dealers without lat/lng stay in the site directory but are not pinned. */
window.TRIPLE_R_DEALERS = [
  { name: "Triple R Trailers (Factory)", city: "Booneville", state: "MS", phone: "(662) 728-7975", lat: 34.6579, lng: -88.5667, factory: true },
  { name: "Ally Automotive", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "American Trailers & Storage", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Andrew", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Beem Pawn & Gun", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "CBM Trailer Sales", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "CDF Customs LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Chickasaw Equipment Co.", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Circle S Transport LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Citadel Storage LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "David's Used Cars", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "DeWitt Tool & Equipment", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Ferrell's Home & Outdoor", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Freedom Outdoors Inc", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Grady's", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "H & R Agri-Power", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Hometown Buildings Plus", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Hoss Trailer Sales", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Jason Dietsch Sales LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Jason Dietsch Trailer Sales Midsouth", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Johnny's 4 Wheelers", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "KDZ Motorsports", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "L & S Golf Carts", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Longrider Supply Co", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "M & S Sales, Inc.", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "MC Trailer Sales", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Main Street Cycle", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Midsouth Trailers, LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Murphy Bros", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Newline Trailers", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Oak Ridge Rentals LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "One Stop Trailer Shop LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Patriot Motorsports LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Pearson's Trailer Parts & Repair Co", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Pfeiffer Sales", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Pleasants Gro & Gen Merchandise", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "RCI", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Rival Feed & Seed LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Royal Trailer Sales", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Saunders Equipment", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Service Supply Co", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Shoals Outdoor Sports", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Show-N-Go LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Sid's Trading Co", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Smith's Enterprises", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "TBJ Trailers & Portable Bldgs LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "The Storage Place", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Timberline Trailers LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Tom Miller Motorsports", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Top Dawg Trailer Sales LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Trailer Sales (Maris)", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "True Grit Trading Co", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Uncle Sam's Tire & Auto LLP", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "VIC, LLC dba Stringers", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Vista Trailers LLC", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Waldon Trailers", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Webb Machine & Supply", city: "", state: "", phone: "", lat: null, lng: null },
  { name: "Wood Sales, Inc.", city: "", state: "", phone: "", lat: null, lng: null },
];
